#---------------------------------------------------------------------
# Controllers for mia hand hw interface v1.0 
#---------------------------------------------------------------------
  

#mia_hand:
  
#---------------------------------------------------------------------
# Publish all joint states -----------------------------------
#---------------------------------------------------------------------
  
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

#------------------------------------------------------------------
# JointPosition Controllers ---------------------------------------
#---------------------------------------------------------------------
    
  j_thumb_fle_position_controller:
    type: position_controllers/JointPositionController
    joint: j_thumb_fle
    
  j_index_fle_position_controller:
    type: position_controllers/JointPositionController
    joint: j_index_fle
    
  j_mrl_fle_position_controller:
    type: position_controllers/JointPositionController
    joint: j_mrl_fle
    

        
#------------------------------------------------------------------
# JointVelocity Controllers ---------------------------------------
#---------------------------------------------------------------------
    
  j_thumb_fle_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: j_thumb_fle
    
  j_index_fle_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: j_index_fle
    
  j_mrl_fle_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: j_mrl_fle
    
  j_thumb_opp_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: j_thumb_opp
 
