#---------------------------------------------------------------------
# Traj Controllers for mia hand hw interface v1.0
#---------------------------------------------------------------------


#mia_hand:

#------------------------------------------------------------------
# Trajectory Position Controllers ---------------------------------------
#--------------------------------------------------------------------

  # joint (actionlib) trajectory controller
  # check http://wiki.ros.org/joint_trajectory_controller
  mia_hand_hw_pos_trajectory_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - j_index_fle
        - j_mrl_fle
        - j_thumb_fle


      constraints:
        goal_time: 4.0
        stopped_velocity_tolerance: 1.0
        j_index_fle:
          goal: &goal_tp_constraint 0.5
          trajectory: &trajectory_tp_constraint 1.0
        j_mrl_fle:
          goal: *goal_tp_constraint
          trajectory: *trajectory_tp_constraint
        j_thumb_fle:
          goal: *goal_tp_constraint
          trajectory: *trajectory_tp_constraint

      stop_trajectory_duration: 1.0

#--------------------------------------------------------------------------------------------------------------------------------------------------------------


#------------------------------------------------------------------
# Trajectory Velocity Controllers ---------------------------------------
#--------------------------------------------------------------------

  # joint (actionlib) trajectory controller
  # check http://wiki.ros.org/joint_trajectory_controller
  mia_hand_hw_vel_trajectory_controller:
      type: velocity_controllers/JointTrajectoryController
      joints:
        - j_index_fle
        - j_mrl_fle
        - j_thumb_fle


      constraints:
        goal_time: 4.0
        stopped_velocity_tolerance: 1.0
        j_index_fle:
          goal: &goal_tv_constraint 0.5
          trajectory: &trajectory_tv_constraint 1.0
        j_mrl_fle:
          goal: *goal_tv_constraint
          trajectory: *trajectory_tv_constraint
        j_thumb_fle:
          goal: *goal_tv_constraint
          trajectory: *trajectory_tv_constraint


      gains:
        j_index_fle:
          p: &p_tvi_gain 1.3
          i: &i_tvi_gain 2.0
          d: &d_tvi_gain 0.2
          antiwindup: &a_tvi_value false
          i_clamp_max: &i_tvi_clamp_max_value 10.0
          i_clamp_min: &i_tvi_clamp_min_value 0.03
        j_mrl_fle:
          p: &p_tv_gain 4.0
          i: &i_tv_gain 2.0
          d: &d_tv_gain 0.2
          antiwindup: &a_tv_value false
          i_clamp_max: &i_tv_clamp_max_value 10.0
          i_clamp_min: &i_tv_clamp_min_value 0.03
        j_thumb_fle: { p: *p_tv_gain, i: *i_tv_gain, d: *d_tv_gain, antiwindup: *a_tv_value, i_clamp_max: *i_tv_clamp_max_value, i_clamp_min: *i_tv_clamp_min_value}

      velocity_ff:
        j_index_fle: 1.4
        j_mrl_fle: 1.4
        j_thumb_fle: 1.4

      stop_trajectory_duration: 1.0
